# Generated by Django 3.0.3 on 2020-09-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20200608_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studypost',
            name='selftext',
            field=models.CharField(default='Self text', max_length=2000000),
        ),
    ]
