# Generated by Django 3.0.3 on 2022-03-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0012_auto_20220317_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studypost',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
