# Generated by Django 3.0.3 on 2022-03-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0013_auto_20220317_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='issue',
            field=models.CharField(default='Post Issue', max_length=500),
        ),
    ]
