# Generated by Django 3.0.3 on 2023-10-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0015_auto_20230914_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='rewrite',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
