# Generated by Django 3.0.3 on 2021-01-15 16:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20200917_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studypost',
            name='selftext',
        ),
        migrations.RemoveField(
            model_name='studypost',
            name='title',
        ),
        migrations.AddField(
            model_name='studypost',
            name='Argument',
            field=models.TextField(default='Source', max_length=10000),
        ),
        migrations.AddField(
            model_name='studypost',
            name='targets',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
