# Generated by Django 3.0.3 on 2021-01-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20210115_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studypost',
            old_name='Argument',
            new_name='source',
        ),
    ]
