# Generated by Django 3.0.3 on 2023-12-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0015_auto_20230914_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studypost',
            name='rewrite_a',
        ),
        migrations.RemoveField(
            model_name='studypost',
            name='rewrite_b',
        ),
        migrations.AddField(
            model_name='studypost',
            name='rewrite',
            field=models.TextField(default='Rewrite', max_length=10000),
        ),
    ]
