WANDB_MODE=offline torchrun --nproc_per_node=4 --master_port=4321 ../repo/stanford_alpaca/train.py \
    --model_name_or_path "EleutherAI/gpt-j-6B" \
    --data_path ../repo/stanford_alpaca/alpaca_data.json \
    --bf16 True \
    --output_dir ../../data/models/instruction-finetuning/gpt-j-6B-instruct \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'GPTJBlock' \
    --tf32 True
