# Generated by Django 3.0.3 on 2021-01-15 16:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20210115_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studypost',
            name='targets',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
