# Generated by Django 3.0.3 on 2021-01-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_annotation_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='best_conclusion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
