# Generated by Django 3.0.3 on 2022-03-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_annotation_best_conclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studypost',
            name='targets',
            field=models.TextField(default='Issue', max_length=500),
        ),
    ]
