# Generated by Django 3.0.3 on 2022-03-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0011_auto_20220317_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='best_conclusion',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='studypost',
            old_name='targets',
            new_name='issue',
        ),
    ]
