# Generated by Django 3.0.3 on 2023-09-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0014_auto_20220317_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='studypost',
            name='rewrite_a',
            field=models.TextField(default='Rewrite_a', max_length=10000),
        ),
        migrations.AddField(
            model_name='studypost',
            name='rewrite_b',
            field=models.TextField(default='Rewrite_b', max_length=10000),
        ),
    ]
